### ISSUE TITLE
Grid not working in a form submission view 

### ISSUE THREAD

**Issue by felixcheruiyot** [formio/ngFormio#206]
I have the following `form schema` which has a grid component called `products`

**Schema/Form**

`{"components":[{"type":"columns","conditional":{"when":null,"eq":"","show":null},"input":false,"key":"Test","columns":[{"components":[{"suffix":"","persistent":true,"inputType":"text","inputMask":"","key":"firstname","defaultValue":"","multiple":false,"prefix":"","input":true,"tableView":true,"type":"textfield","unique":false,"placeholder":"","validate":{"custom":"","customPrivate":false,"required":true,"maxLength":"","pattern":"","minLength":""},"conditional":{"when":null,"eq":"","show":null},"label":"First name","protected":false}]},{"components":[{"suffix":"","persistent":true,"inputType":"text","inputMask":"","key":"lastname","defaultValue":"","multiple":false,"prefix":"","input":true,"tableView":true,"type":"textfield","unique":false,"placeholder":"","validate":{"custom":"","customPrivate":false,"required":false,"maxLength":"","pattern":"","minLength":""},"conditional":{"when":null,"eq":"","show":null},"label":"Last name","protected":false}]}],"lockKey":true},{"suffix":"","multiple":false,"inputType":"text","inputMask":"","defaultValue":"","key":"bela","prefix":"","persistent":true,"input":true,"tableView":true,"type":"textfield","unique":false,"placeholder":"","validate":{"custom":"","customPrivate":false,"required":false,"minLength":"","pattern":"","maxLength":""},"conditional":{"when":null,"eq":"","show":null},"label":"Bela","protected":false},{"type":"panel","title":"Panel 2","theme":"default","components":[{"dir":"applications","conditional":{"when":null,"eq":"","show":null},"defaultValue":"","key":"upload","multiple":false,"url":"/upload","storage":"url","tableView":true,"input":true,"type":"file","placeholder":"","persistent":true,"label":"Upload","protected":false},{"suffix":"","inputType":"number","conditional":{"when":null,"eq":"","show":null},"defaultValue":0,"prefix":"","isNew":false,"key":"age","input":true,"tableView":true,"type":"number","validate":{"custom":"","integer":"","max":"","step":"any","multiple":"","required":false,"min":""},"placeholder":"","persistent":true,"label":"Age","protected":false},{"enableDate":true,"persistent":true,"datepickerMode":"day","format":"yyyy-MM-dd","datePicker":{"minMode":"day","initDate":"","datepickerMode":"day","showWeeks":true,"maxMode":"year","yearRange":"20","startingDay":0},"key":"dateapplied","timePicker":{"arrowkeys":true,"minuteStep":1,"readonlyInput":false,"hourStep":1,"mousewheel":true,"showMeridian":false},"input":true,"tableView":true,"type":"datetime","validate":{"custom":"","required":false},"placeholder":"","enableTime":false,"conditional":{"when":"age","eq":"20","show":true},"label":"Date applied","protected":false}],"conditional":{"when":null,"eq":"","show":null},"input":false},{"tableView":true,"label":"","type":"container","tree":true,"components":[{"tableView":true,"label":"Products","type":"datagrid","tree":true,"components":[{"suffix":"","persistent":true,"inputType":"text","inputMask":"","key":"name","defaultValue":"","hideLabel":true,"multiple":false,"input":true,"tableView":true,"type":"textfield","prefix":"","unique":false,"placeholder":"","validate":{"custom":"","customPrivate":false,"required":false,"maxLength":"","pattern":"","minLength":""},"conditional":{"when":null,"eq":"","show":null},"label":"Name","protected":false},{"suffix":"","inputType":"text","inputMask":"","key":"price","defaultValue":"","hideLabel":true,"conditional":{"when":null,"eq":"","show":null},"prefix":"","input":true,"tableView":true,"type":"currency","validate":{"custom":"","multiple":"","required":false},"placeholder":"","persistent":true,"label":"Price","protected":false},{"suffix":"","inputType":"number","key":"qty","defaultValue":0,"hideLabel":true,"conditional":{"when":null,"eq":"","show":null},"prefix":"","input":true,"tableView":true,"type":"number","validate":{"custom":"","integer":"","max":"","step":"any","multiple":"","required":false,"min":""},"placeholder":"","persistent":true,"label":"Qty","protected":false}],"input":true,"persistent":true,"key":"products2","protected":false,"conditional":{"when":null,"eq":"","show":null}}],"input":true,"persistent":true,"key":"products","protected":false,"conditional":{"when":null,"eq":"","show":null}},{"size":"md","leftIcon":"","rightIcon":"","label":"Submit","key":"submit","conditional":{"when":null,"eq":"","show":null},"tableView":false,"type":"button","theme":"primary","action":"submit","block":false,"disableOnInvalid":true,"input":true}],"page":0,"_id":"67"}`

**Submission**

`{"data":{"dateapplied":"2016-09-14T21:00:00.000Z","bela":"200","age":20,"upload":[],"firstname":"Felix","products":{"products2":[{"name":"One","qty":1,"price":"20"},{"name":"Two","qty":1,"price":"30"},{"name":"Three","qty":10,"price":"50"}]},"lastname":"Cheruiyot"}}`

**How I'm calling the directive:**

`<formio-submission form="form" submission="submission"></formio-submission>`

Initializing the app

`var formBuilder = angular.module('formApp', ['formio']).run(["$rootScope", 'formioComponents', '$timeout',
            function ($rootScope, formioComponents, $timeout) {

```
        }]);

    formBuilder.controller('FormCtrl', ['$scope', 'formioComponents', '$timeout',
        function ($scope, formioComponents, $timeout) {
            $scope.submission = null;
            $scope.form = null;
            $scope.ticket_id = window.location.pathname.split('/')[3];

            $scope.loadTicket = function () {
                //Fetch workflow data from the server and feed the schema details
                App.remoteGet('/api/v1/tickets/' + $scope.ticket_id, {}, function (res) {
                    $scope.submission = res.form_data;

                    //Add form and append id to it
                    $scope.form = res.schema;
                    $scope.form['_id'] = $scope.ticket_id;

                    $scope.$apply();
                }, function (err) {
                    console.log(err);
                    App.notifyUser('error', 'Error fetching ticket data')
                })
            };
        }])`
```

**Output**

![formio](https://cloud.githubusercontent.com/assets/1054590/18308347/c99e3e32-74fc-11e6-854c-20c40d14265d.png)

**Problem**

Note the grid is not shown in the above output

**Comment by zackurben** [comment]
@felixcheruiyot thanks for reporting this, we will look into it.
