### ISSUE TITLE
Survey do not restore state

### ISSUE THREAD

**Issue by adascal** [formio/ngFormio#215]
I added new survey on form, and then I try to open submission, only last value is selected

**Comment by vikaswizorbit** [comment]
Did we have any solution of this issue?

**Comment by travist** [comment]
I am able to reproduce this. We have added it to our backlog, but I suspect it may have something to do with the names added to the survey component inputs.

We will look into it eventually, unless someone from the community wishes to tackle it.

**Comment by adascal** [comment]
I tried different names, and managed to reproduce problem on form.io portal. So without 3d part code.

**Comment by travist** [comment]
What is strange is that if you hard refresh your browser, the state is fully restored. It seems like it is either a race condition (hard to fix) or $scope.$apply() (easy).  We will experiment with both as soon as we are able to come up for air. :)

**Comment by travist** [comment]
I have a fix for this @ https://github.com/formio/ngFormio/pull/242, but it is kind of a hack. I am not sure why the values are not binding correctly, but this may be a bug deep in the Angular.js code.
