### ISSUE TITLE
DateTime component default value overwrites form data

### ISSUE THREAD

**Issue by blackbaud-jeremymorgan** [formio/ngFormio#266]
Codepen for reference: http://codepen.io/blackbaud-jeremymorgan/pen/WogMeM

It seems that the "default" field is always set in the model, whether or not there is a preexisting value.

**Comment by zackurben** [comment]
@blackbaud-jeremymorgan thanks for the report, I'll get that into the backlog.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
