### ISSUE TITLE
Drawing from other form controls in custom validation

### ISSUE THREAD

**Issue by blackbaud-jeremymorgan** [formio/ngFormio#285]
Hey all,

Just wondering, how would I go about validating fields based on other fields in the same form? Like, for example, having a `start time` and `end time` field, how would I validate that the `end time` comes after the `start time`?

**Comment by lookatmypinky** [comment]
`valid = ( '{{ startTime }}' < '{{ endTime }}' ) ? true : 'anachronism';`

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
