### ISSUE TITLE
Form rendering 

### ISSUE THREAD

**Issue by desmondCreed** [formio/ngFormio#313]
formio rendering using  src="'http://localhost:8107/api/forms/1'"(this is api call to json schema of form from DB) from my server is not working.
But if use src="'https://yjjwubnkdmwcedm.form.io/customer'" from Form.io works properly.

**Comment by zackurben** [comment]
@desmondCreed This library can render JSON forms stored in your db, but they need to conform to the same standard or nothing will render.

**Comment by prashant93** [comment]
I didn't not understand your answer.please can you explain me in detail what standard
