### ISSUE TITLE
URL file upload bug and workaround

### ISSUE THREAD

**Issue by krixerx** [formio/ngFormio#322]
URL uploading is complaining in current ng-formio version: 
"File Upload URL not provided".
Althought url attribute is provided and storage type is "url".

The problem:
$scope.formio is not initialized because src attribute is empty in ng-formio element.

I suspect, problem location is here:
// FOR-71
        if (!$scope._src && !$scope.builder) {
          $scope.$watch('src', function(src) {
            if (!src) {
              return;
            }
            $scope._src = src;
            $scope.formio = FormioScope.register($scope, $element, {
              form: true,
              submission: true
            });
          });
        }

The workaround is to just put something into src attribute value:
`<formio form="formFile" src="'something'" submission="submission"></formio> `

**Comment by richardgundersen** [comment]
Hi, does this affect the Dropbox integration too? I'm getting the same error even though I'm apparently hooked up to Dropbox.

**Comment by gkarnaty** [comment]
Unable to upload a file even after proving the storage and url,
giving this error "File Upload URL not provided."

In demo also fileupload is not working,
can you let me know where to initialize the fileupload

**Comment by KknowledgeInfo** [comment]
![dsc06486](https://user-images.githubusercontent.com/14926603/38891746-dba82ef6-42a2-11e8-99b6-e4cbc16fe236.JPG)

**Comment by Nickolos16** [comment]
Any update regarding on this ?   Althought url attribute is provided and storage type is "url" I still encountered error "File Upload URL not provided" i tried the work around that @krixerx  suggestion but i still got error

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
