### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by LeMamin** [formio/ngFormio#327]
Hello,

from the this commit @AbdallaMohamed  : SHA: f43b4bcd18da42611294177a7600fc684348b96e
https://github.com/formio/ngFormio/commit/f43b4bcd18da42611294177a7600fc684348b96e

I have a issue on my custom translation (for exemple in servicetracker app). My translation is
empty like this `{}`.

**updated**
The problem is in the src/filters/translate.js : `return $translate(text)` (promise)

The translate filter doesn't work: `{{ "Day" | formioTranslate:null:builder }} `

**Comment by LeMamin** [comment]
@AbdallaMohamed 
The problem is in the src/filters/translate.js : `return $translate(text)` (promise)

The translate filter doesn't work: `{{ "Day" | formioTranslate:null:builder }} `

**Comment by AbdallaMohamed** [comment]
@LeMamin Do you suggest using the $filter service instead of $translate? https://angular-translate.github.io/docs/#/api/pascalprecht.translate.filter:translate

**Comment by LeMamin** [comment]
@AbdallaMohamed Since version 2.0.0 $translate('key') returns an promise!

You can use `return $translate.instant(text)` to getting the translation right away without waiting for a promise (use the service in sync). Can you do a pull request?
https://angular-translate.github.io/docs/#/guide/21_migration-guide

Thanks

**Comment by AbdallaMohamed** [comment]
@LeMamin Thanks for committing that.

**Comment by LeMamin** [comment]
@AbdallaMohamed the PR was merge : https://github.com/formio/ngFormio/pull/331
