### ISSUE TITLE
Is it possible to create custom fields?

### ISSUE THREAD

**Issue by tobz-nz** [formio/ngFormio#328]
I'm try to create a custom field & not sure how easy/hard/possible it is to do. I'm pretty inexperienced with angular which is probably half my problem.

Can anyone point me in the right direction?

**Comment by prashant93** [comment]
please have look to #332. Close this let me know if any issue.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
