### ISSUE TITLE
Select Component Default Values not working for some Data Source Types

### ISSUE THREAD

**Issue by willemderu** [formio/ngFormio#335]
The Select Component 'Default Value' setting is not working for some 'Data Source Types'. For example, for the 'Custom' Data Source Type it is not working: https://www.screencast.com/users/willemd2999/folders/Share/media/f5175f28-d7b5-4f63-a36d-98341d1d6a83 For the JSON type it is not working either: https://www.screencast.com/users/willemd2999/folders/Share/media/f61b22c7-737d-4946-ad1e-c30383e2298c and it is also not working for the 'Resource' Data Source Type.

(It does work for the 'Values' Data Source Type:  https://www.screencast.com/users/willemd2999/folders/Share/media/9d19b4e6-473e-4b6a-bb43-c1190b640870)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
