### ISSUE TITLE
formrender readonly prorperty is not working for custom component

### ISSUE THREAD

**Issue by prashant93** [formio/ngFormio#347]
Date range is a custom componet added by me.

![image](https://cloud.githubusercontent.com/assets/4151470/25388021/40c8e8ca-29ea-11e7-9e31-45ac0f93f19d.png)
You can see  day component is readonly but Date range is not.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
