### ISSUE TITLE
daterange issue

### ISSUE THREAD

**Issue by prashant93** [formio/ngFormio#348]
I think you forgot to add  comma after  yearColumns: 5

 -            yearRange: '20',
 +            yearRows: 4,
 +            yearColumns: 5
              minDate: null,
              maxDate: null

**Comment by travist** [comment]
This has just been fixed. Thanks.

**Comment by prashant93** [comment]
But after update mindate and maxdate is not retaining on reload of datetime component.
if set the mindate and maxdate but it's not binding
![image](https://cloud.githubusercontent.com/assets/4151470/25395122/aec37b8e-29fd-11e7-9fe9-e7787108a2fd.png)
