### ISSUE TITLE
Select component does not work when refreshOn is set to Any Changes

### ISSUE THREAD

**Issue by sbalay** [formio/ngFormio#362]
In select component, setting the `refreshOn` property to `Any Changes` breaks the component behaviour when using JSON or URL as datasource. The component never gets initialised, and does not get populated after changes on other inputs.

I think this maybe caused by these lines of code in file `src/components/select.js`.

```js
if (settings.refreshOn) {
  if (settings.refreshOn === 'data') {
    $scope.$watch('data', refreshItemsWhenReady, true);
    return; // HERE! Remember this return statement
  }

  $scope.$watch('data.' + settings.refreshOn, refreshItemsWhenReady);
  $scope.$watch('submission.data.' + settings.refreshOn, refreshItemsWhenReady);
}
```

I think so because above those lines, the refresh items function is defined like this:

```js
$scope.refreshItems = function() {
  return $q.resolve([]);
};
```

And below those lines, refreshItems is redefined according to the selected datasource:

```js
switch (settings.dataSrc) {
  ...
  case 'json':
    ...
    $scope.refreshItems = function(input, url, append) {
       ...
    }
  case 'url':
  case 'resource':
    ...
    $scope.refreshItems = function(input, newUrl, append) {
      ...
    }
    ...
}
```

When `Any Changes` is selected, `settings.refreshOn` will be `'data'`. Because of that, the return in [line 258](https://github.com/formio/ngFormio/blob/master/src/components/select.js#L258) does not allow `$scope.refreshItems` to be redefined according to the datasource, producing this unexpected behaviour.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
