### ISSUE TITLE
Add Another button not disabled when using read-only, nor hidden when using hide-components

### ISSUE THREAD

**Issue by johan--** [formio/ngFormio#366]
When using the following parameters when displaying submissions, the Submit button on a form is hidden:

read-only=true
hide-components = ['submit']

It is also disabled when using read-only without using 'hide-components' .

Yet, the Add Another button remains visible when the above parameters are set.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
