### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by ohrechnikov** [formio/ngFormio#367]
On the form there is **text input field**, with no validations.
All data from the form saved in external DB.
In case User input some number in this field and Submit the form, the form submitted with no issues and data successfully  collected from the form.
User open the form with saved data. (Data loaded from DB and passed to form)
Previously saved number, is correctly displayed in the text input field.
When User hit Submit button, the validation occurs:
"CC060 must be longer than -1 characters."

It seems the field is going to be validated(even no validation is configured) **only if the entered value is numeric.**

Please take a look on attached screenshot:
![val_iss_1](https://cloud.githubusercontent.com/assets/28706955/26058734/d38f28a2-3987-11e7-9447-077258e8d94b.jpg)

**Comment by anupriya7295** [comment]
We are also facing the same issue ,kindly give solution as early as possible

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
