### ISSUE TITLE
No validation messages in survey components nor error highlighting

### ISSUE THREAD

**Issue by CatBakun** [formio/ngFormio#379]
When a survey has required fields, a general error is shown for the form on submit. But no indication in the survey component. It confuses the users in long forms, because they can not easily identify the error that does not allow them to submit the form.

![image](https://cloud.githubusercontent.com/assets/4873355/26504258/33f4ae98-421a-11e7-9637-e76f8dbe4517.png)

**Comment by randallknutson** [comment]
Merged
