### ISSUE TITLE
Update form components issue rendering 

### ISSUE THREAD

**Issue by ghachemsaif** [formio/ngFormio#397]
Hello, I have a probleme when updating my form with the **rendering**. 
This is the function that update the **$rootScope.form**
`$scope.change = function () {
        $rootScope.form = {"components":[{"input":true,"tableView":true,"inputType":"number","label":"Numéro point d'analyse","key":"numropointdanalyse","placeholder":"numéro point d'analyse","prefix":"","suffix":"","defaultValue":"","protected":false,"persistent":true,"hidden":false,"clearOnHide":true,"validate":{"required":false,"min":"","max":"","step":"any","integer":"","multiple":"","custom":""},"type":"number","$$hashKey":"object:207","tags":[],"conditional":{"show":"","when":null,"eq":""}},{"input":true,"inputType":"checkbox","tableView":true,"hideLabel":true,"label":"Présence sur le cheminement d'un obstacle non permanent ?","datagridLabel":true,"key":"prsencesurlecheminementdunobstaclenonpermanent","defaultValue":false,"protected":false,"persistent":true,"hidden":false,"name":"","value":"","clearOnHide":true,"validate":{"required":false},"type":"checkbox","$$hashKey":"object:247","tags":[],"conditional":{"show":"","when":null,"eq":""}},{"input":true,"tableView":true,"inputType":"text","inputMask":"","label":"Quantitatif :","key":"quantitatif","placeholder":"Quantitatif","prefix":"","suffix":"","multiple":false,"defaultValue":"","protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"validate":{"required":false,"minLength":"","maxLength":"","pattern":"","custom":"","customPrivate":false},"conditional":{"show":"","when":null,"eq":""},"type":"textfield","$$hashKey":"object:379","tags":[]},{"input":true,"tableView":true,"label":"Notes","key":"message","placeholder":"Ajouter une note","prefix":"","suffix":"","rows":3,"multiple":false,"defaultValue":"","protected":false,"persistent":true,"validate":{"required":false,"minLength":"","maxLength":"","pattern":"","custom":""},"type":"textarea","conditional":{"show":"","when":null,"eq":""},"$$hashKey":"object:19","hidden":false,"wysiwyg":false,"clearOnHide":true,"tags":[]},{"type":"button","theme":"primary","disableOnInvalid":true,"action":"submit","block":false,"rightIcon":"","leftIcon":"","size":"md","key":"submit","tableView":false,"label":"Submit","input":true,"$$hashKey":"object:20"}],"display":"form"}
    }`

Here is my code : 
https://jsfiddle.net/ktosxhou/

click in the top button to fire the change event

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
