### ISSUE TITLE
Required file component validation is not working.

### ISSUE THREAD

**Issue by krixerx** [formio/ngFormio#398]
We are using the latest ng-formio library.
File component is configured as required field.
But no validation error is occurred when submit button is pressed and file field is empty.

**Comment by rmckeel** [comment]
I'm also interested in this bug.  I'd be happy to review the fix when it's in place.

**Comment by hrz11** [comment]
Any update on this one? Would like to use this functionality.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
