### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by tjgibbs92** [formio/ngFormio#402]
If there is an error in the form, it throws the Fix following errors. Great, I fix the errors and submit it again with no errors and it still says errors remain.

I think the issue lies in that the form is no longer considered pristine and it doesn't go through the validation again to check the form.

I'm finding it in formio.js in $scope.checkErrors() starting around line 12754 in v2.19.5.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
