### ISSUE TITLE
ngFormio Renderer - Wizard Titles Overlap

### ISSUE THREAD

**Issue by elma6394** [formio/ngFormio#490]
![image](https://user-images.githubusercontent.com/17027941/31848465-b51b41e8-b601-11e7-82fc-355aa54c4727.png)

is there a way to show the wizard step titles on the left side and the rendered elements on the right side?
I have form step titles that are long and they overlap, making the rendered form look ugly.

i don't want to hack around to move the step titles to the left if there is an option that does it in a cleaner way.

Thanks

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
