### ISSUE TITLE
onChange event for dropdown

### ISSUE THREAD

**Issue by h123eranga** [formio/ngFormio#491]
How to use onChange event in ngFormio library. Its available only for js and angular 2, 4. What is the syntax to use onChnage for formio.

js
form.on("change", (change)=>{

});

**Comment by ens121** [comment]
Same issue here.

**Comment by hardfi** [comment]
` <formio [form]="formioForm" (change)="onChange($event)"></formio>`

And if you're using formio.js library:

```
 formioBuilderInit() {
    Formio.builder(document.getElementById('builder'), {components: this.formioComponents})
        .then(form => {
            form.on('change', value => {
                 action...
            })
        });
 }
```

**Comment by kamsi** [comment]
Well, looking at the spec for events: https://github.com/formio/ngFormio/wiki/Responding-to-Form-Events
it would seem that there is no way to listen to "change" event in ngFormio. I also would like to know if/how one can listen to that event. Also (but maybe it should be a separate issue) I would like to know how can I get handle on the native formio object from withing ngFormio (which would enable me to listen to the "change" on that object in a pretty straightforward way of course).

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
