### ISSUE TITLE
<formio> does not show up

### ISSUE THREAD

**Issue by WWWW-W** [formio/ngFormio#542]
I installed and imported all the dependencies

I not only use the full installation method
<link rel="stylesheet" href="https://rawgit.com/formio/ngFormio/master/dist/formio-full.min.css" />
<script src="https://rawgit.com/formio/ngFormio/master/dist/formio-full.min.js"></script>
but also use the basic installation method and use wiredev to import all the dependecies in the index.html

I put <formio src="'https://gbxfzcylnrikthh.form.io/test'"></formio>, it just does not show up.

And the console gives me a lot of errors related to the import of all the dependencies, e.g.
1.angular-sanitize.js:602 Uncaught TypeError: angular.module(...).provider(...).info is not a function
2.Error: [$compile:iscp] http://errors.angularjs.org/1.3.13/$compile/iscp?p0=formio&p1=options&p2=%3C
3.agular.js:11607 Error: [$injector:unpr] http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24animateCssProvider%20%3C-%20%24animateCss%20%3C-%20.item-animation

**Comment by travist** [comment]
Please compare what you have to http://formio.github.io/ngFormio/simple.html which shows it working in Angular 1.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
