### ISSUE TITLE
Formio still supports Angular1?

### ISSUE THREAD

**Issue by ziwenzhao** [formio/ngFormio#543]
I wonder if formio still supports angular1 because after a lot of trial, i still cannot get <formio> or <formio-builder> shown on the webpage.

I generated a Angular1 project from form.io's website, and I believe this automatically generated project they give me should have all the dependencies, and I just put <formio> and <formio-builder> in html. It just does not show up.

Regards,
Ziwen

**Comment by travist** [comment]
Yes it still supports Angular 1. Please compare what you have with http://formio.github.io/ngFormio/simple.html

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
