### ISSUE TITLE
Cancel file upload while still uploading error: Cannot set property 'status' of undefined

### ISSUE THREAD

**Issue by masmerino13** [formio/ngFormio#555]
If click on X icon while the file upload still running (see img below)

![image](https://user-images.githubusercontent.com/4874090/36269948-1cc6f96e-1240-11e8-873d-d50a1f1bed2d.png)

Error:
```
Uncaught TypeError: Cannot set property 'status' of undefined
    at XMLHttpRequestUpload.
```

The error is generated here:
https://github.com/formio/ngFormio/blob/master/src/components/file.js#L259

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
