### ISSUE TITLE
Select Component does not allow typeahead data to refresh Default Value

### ISSUE THREAD

**Issue by blackbaud-KelbyStine** [formio/ngFormio#599]
Description: When updating a form field where the default value is set, selecting a new item from the typeahead search list does not replace the default value. It is only possible to update the select value when scrolling through the standard dropdown list and clicking an item.

1. Set up a form that uses the Select Component (Data source URL) and a valid default value.
2. Navigate to the form, and note that the default value is set
![1](https://user-images.githubusercontent.com/16121843/40316845-38cc4232-5ce5-11e8-9438-379205106aac.png)
3. Click on the dropdown, the standard drop down should appear
4. Type in another valid select option, the typeahead search dropdown appears with results
![2](https://user-images.githubusercontent.com/16121843/40316899-5cd0ee58-5ce5-11e8-810e-21a47090aa03.png)
5. Choose one of the typeahead dropdown options (either by keyboard or mouse click)
6. After the option is chosen the typeahead dropdown disappears, but the default value remains
![3](https://user-images.githubusercontent.com/16121843/40316925-70387f4c-5ce5-11e8-819d-68cd59ee4ab9.png)

Other aspects to note: This bug does not happen when the source is the JSON file. All other settings of the component are default, except where needed to take in the URL data.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
