### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module formio

### ISSUE THREAD

**Issue by cegithub** [formio/ngFormio#605]
I am trying to integrate form io in ionic application.

I have installed ngformio using "npm install --save ng-formio". and include dependency in app.js file.Now while running project,
 I am getting error "Error: [$injector:modulerr] Failed to instantiate module formio".

**Comment by anupriyaideas2it** [comment]
You have to inject formio module as below in ionic1 ,before injecting this ,check whether you are having formio library in node_modules 

`var app = angular.module('samplemodule', ["ionic","formio"]);`
