### ISSUE TITLE
how to translate formio?(i am new to angularjs and web development)

### ISSUE THREAD

**Issue by hossein69** [formio/ngFormio#624]
hello it seems to be silly question but
i want to translate formio editor,
i dont see a controller at all.
i findout that there is filter name formiotranslate for example:
{{'Radio Value' | formioTranslate}}
i dont know how to use it to translate editor.
i wrote this in translateor.js  
var appp = angular.module('formioApp');
var f = appp.filter(formioTranslate);
f.addLanguage('es', esTranslation);
 f.use('es');
var esTranslation = {
  'Submit': 'Enviar',
  'Language': 'Idioma',
  'Translations': 'Traducciones',
  'First Name': 'Tu nombre',
  'Last Name': 'Apellido',
  'Enter your email address': 'Ingrese su dirección de correo electrónico',
  'Enter your first name': 'Ponga su primer nombre',
  'Enter your last name': 'Ingresa tu apellido',
  'Valid Email Address': 'dirección de email válida',
  'Please correct all errors before submitting.': 'Por favor, corrija todos los errores antes de enviar.',
  'required': '{{field}} es requerido.',
  'invalid_email': '{{field}} debe ser un correo electrónico válido.',
  'error': 'Por favor, corrija los siguientes errores antes de enviar.'
};
and editor didn't show at all.

**Comment by travist** [comment]
We have documentation on how to translate @ 

https://help.form.io/tutorials/walkthroughs/translations/
https://help.form.io/tutorials/walkthroughs/resource/
https://help.form.io/tutorials/walkthroughs/phraseapp/
