### ISSUE TITLE
Populating Data To a Form using (Formio) 

### ISSUE THREAD

**Issue by Nickolos16** [formio/ngFormio#628]
Hi everyone ,

I am having this difficulty on rendering the form with its submission data  As per instruction on this Site 
https://help.form.io/faq/advanced/  iv'e used the method #2 on **Populating Data To a Form** for me to be able to control the data that will display with form.

<formio src="'https://myproject/myform'" submission="submission"></formio>

$scope.submission = {data: { firstName: ‘Travis’, lastName: ‘Tidwell’ }};

but after i use that method its still not rendering the form with its data that i set ?  is this a bug or what ?

please help thanks.
#formio

**Comment by wag110894** [comment]
Hello Nickolos,
 
William here again with Form.io support. Thanks for reaching out! 
 
This should be working. You can try reloading the form and setting <formio form="form" submission="submission" url="formUrl" />.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by Nickolos16** [comment]
Hi @wag110894  

this is my code on my View Page 

<formio form="surveyForm"  submission="submission"></formio>

and this is my code on my Controller Java Script

$scope.submission= {data: { firstName: ‘Travis’, lastName: ‘Tidwell’ }}; // data that i want to render with the form

$scope.surveyForm = template;  // the form that i create  saved and being fetch from my database

-------------------------------------------------------------------------------------------------------------------

but it's still just rendering the a form without its submission data with it ? why it's not working ? i thought As per this instruction on this link https://help.form.io/faq/advanced/  it will automatically populate the form with the data  you declare the on your JavaScript ? 

Please help
#formio

**Comment by wag110894** [comment]
Hello, 
Can you confirm that the firstName and lastName keys match the fields in the form? They will not fill if they do not match. 
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by Nickolos16** [comment]
Thanks for response @wag110894  All is well now , what ive done is i declare $scope.submission = {} on my controller so that my $scope.surveyForm.data will populate automatically the .data from my database.
