### ISSUE TITLE
select component is not working in ios 10.0 on iphone 5 

### ISSUE THREAD

**Issue by akhilesh-sharma168** [formio/ngFormio#631]
Hi,

I noticed a strange behaviour of "select" component in iphone 5 having ios 10.0 .
The issue is reproducible in the above configuration only .
For the same will attach the screenshots also .
So kindly help me out in this issue.

![cio-348](https://user-images.githubusercontent.com/45589364/49432996-f4632380-f7d6-11e8-9010-9c2ae3f2f7f2.jpg)
![cio-348-1](https://user-images.githubusercontent.com/45589364/49432997-f4632380-f7d6-11e8-926c-0bb3b1463ff6.jpg)

**Comment by randallknutson** [comment]
It looks like you aren't including the css for choices.js. You can do it by including https://github.com/formio/formio.js/blob/master/dist/formio.form.css in your application

**Comment by akhilesh-sharma168** [comment]
thanks,@randallknutson your solution worked.
