### ISSUE TITLE
Date of Birth is getting reduced by 1 day after form submission.

### ISSUE THREAD

**Issue by akhilesh-sharma168** [formio/ngFormio#632]
Hi ,
In recent finding , I observed that while submitting the form having datetime component for date of birth the date submitted to the server got reduced by 1 . Why this unusual behaviour ,can someone look into the issue and suggest workaround or a fix.
Form IO version we are using is
**"angular-formio": "^2.0.0-rc.3",**
Thanks,
![screenshot from 2018-12-05 17-10-05](https://user-images.githubusercontent.com/45589364/49511283-bdf9d700-f8b0-11e8-86a0-e7492102e5d3.png)
![screenshot from 2018-12-05 17-03-06](https://user-images.githubusercontent.com/45589364/49511303-c9e59900-f8b0-11e8-8c96-6b327381e34b.png)

**Comment by akhilesh-sharma168** [comment]
Hi Team ,

Can you look into the issue .
This needs to be fixed.

**Comment by travist** [comment]
This is probably a "timezone" issue where it is getting converted to UTC time which is 1 day before. This is fixed in the latest renderer @ https://github.com/formio/formio.js, so I don't believe this would be back-ported to this library since this is now considered legacy.
