### ISSUE TITLE
"File Upload URL not provided." 

### ISSUE THREAD

**Issue by Nickolos16** [formio/ngFormio#633]
Hi can anyone provide a clear guidelines on how to implement the file upload using formio, as a newbie user of ngFormio i am having difficulties on how to set up this function , i try to implement this https://github.com/danialfarid/ng-file-upload#server  but its still giving me an error also i read this instruction under https://help.form.io/integrations/filestorage/#url it's still not clear for me on how to make the file upload working and how to put a custom URL  

can anyone explain or discuss how to set up the File Component in a correct way 

PS. I integrate the ngFormio on my own project not a subscriber for now but planning to, for future use of my project

Thank you

**Comment by Nickolos16** [comment]
tagging you my friend @wag110894

**Comment by Nickolos16** [comment]
Hi randall thanks for response 

First under the File Component -> i set the storage as Url see picture below 

![image](https://user-images.githubusercontent.com/41312653/50126105-7f97eb00-02a6-11e9-8d65-970ab7eaf486.png)

Second as per instruction to follow the guidelines of how to set up an service  https://github.com/danialfarid/ng-file-upload#server  i follow it and put the Upload Url but i dont know if its correct or i am the one who's wrong its still giving me an error , 

 
![image](https://user-images.githubusercontent.com/41312653/50126389-a9054680-02a7-11e9-9dc5-edebffb59fa6.png)

and its always giving me this error whenever i upload it doesn't initialize the Url i put see picture below

 
![image](https://user-images.githubusercontent.com/41312653/50126428-d6ea8b00-02a7-11e9-875c-16e69407c031.png)

**Comment by travist** [comment]
When embedding the form, you need to make sure that you provide the ```url``` parameter to the ```formio``` directive which is used to tell the rendered form which form you are pointing to.

```<formio form="{....}" url="'https://myproject.form.io/myform'"></formio>```

**Comment by Nickolos16** [comment]
Hi @travist thanks for response 

As per your instruction i put my upload URL that is i set on File Components and put the **url** parameter to my <formio> directive , but it seem's not affecting the file upload function  see picture below 



but when i click on the upload url service i created it's working see picture below: 




 is there something that i need to configure on my formio ?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
