### ISSUE TITLE
componentsProvider is deprecated

### ISSUE THREAD

**Issue by molnargabor** [formio/ngFormio#634]
Hello everyone!

I would make a custom component, but it drops a message to the console:
"formioComponents is deprecated"
I would use the formioComponentsProvider.register() method. Can anyone help me, how should I register a new component without this method?
Thx a lot!

**Comment by travist** [comment]
If you want to build custom components for the 3.x branch of this, then you will need to build them within the core renderer which there are docs @ http://formio.github.io/formio.js/app/examples/customcomponent.html
