### ISSUE TITLE
Building wizard with form builder 

### ISSUE THREAD

**Issue by signalarun** [formio/ngFormio#638]
Wizard builder not activated when wizard is selected from dropdown.

**Comment by randallknutson** [comment]
Is this on our beta site? If so, it is a known issue we are working on.

**Comment by signalarun** [comment]
Tried the ngFormio 3.x and found the issue in that.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
