### ISSUE TITLE
Bad webpack external jQuery dependency [BUG] 

### ISSUE THREAD

**Issue by kamsi** [formio/ngFormio#641]
Hi,

I belive that this line:
https://github.com/kamsi/ngFormio/blob/3.x/config/webpack.config.js#L69

should be changed to:
jquery: 'jquery',

as is, it produces the following output to dist/ng-formio:
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("jQuery"));
	else if(typeof define === 'function' && define.amd)
		define(["jQuery"], factory);
	else if(typeof exports === 'object')
		exports["ngformio"] = factory(require("jQuery"));
	else
		root["ngformio"] = factory(root["jQuery"]);
})(window, function(__WEBPACK_EXTERNAL_MODULE_jquery__) {
```

which is wrong, cause there is no "jQuery" module on npm...

You can easily test this by trying to use the dist/ng-formio.js with import in some webpack build. I guess this was never discovered cause it is rare to use webpack with ng-formio but I am :)

**Comment by travist** [comment]
Please submit a pull request.

**Comment by kamsi** [comment]
@travist sure.

https://github.com/formio/ngFormio/pull/642

**Comment by jtamm-red** [comment]
You have to add one thing in file webpack.config.js:

`...
    resolve: {
        alias: {
            'jQuery': 'jquery/dist/jquery'
        },
    }
`

**Comment by randallknutson** [comment]
Thanks. We'll pull this in the next time we do a build.

**Comment by desertmark** [comment]
We also use ng-formio with webpack we're having this trouble as well.

@jtamm-red  solution works.
