### ISSUE TITLE
Feature Request: Proper i18n handling (over Service Provider and/or Injection)

### ISSUE THREAD

**Issue by Venipa** [formio/ngFormio#645]
We tried changing languages several times including window.navigator language.
No change has been made to formio (language property does not even work).

Tho you framework is good enough for people who make only en lang use.

**Comment by randallknutson** [comment]
Our library does support multiple languages with i18n. We don't automatically switch though. Here is an example of how to make it work: http://formio.github.io/formio.js/app/examples/language.html

**Comment by Venipa** [comment]
That's not what I meant tho that example is not build according to best practice on changing languages.

How about adding a service provider to with a method that changes the language or a factory to build an own provider and to implement own changes.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
