### ISSUE TITLE
CKEditor call fails for Content Component [BUG] 

### ISSUE THREAD

**Issue by christophermurphy2-veradigm** [formio/ngFormio#646]
# Environment

Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
    - Version: ~3.20.0
  - [ ] Form.io
- Formio.js version: ^3.24.0 (only as the dependency for this repo)
- Frontend framework: Angular.js
- Browser: Any
- Browser version: Any

## Steps to Reproduce

1. In the builder, add a Content component.

## Expected behavior

Component loads ckeditor.

## Observed behavior

After the call to get the ckeditor fails, the component cannot be interacted with to create content as expected.

## Example

GET <https://cdn.staticaly.com/gh/formio/ckeditor5-build-classic/v12.2.0-formio.2/build/ckeditor.js> net::ERR_ABORTED 503

### When going directly to the url

Error 503 Service Unavailable

Service Unavailable
Guru Mediation:

Details: cache-mdw17338-MDW 1564410098 2568529691

Varnish cache server

### Other observations

It seems that there was a v12.2.0-formio.2 release made on 7/2/2019, but the page the cdn refers to does not exist in GitHub.
<https://github.com/formio/ckeditor5-build-classic/v12.2.0-formio.2/build/ckeditor.js> returns 404.

**Comment by randallknutson** [comment]
It appears that staticaly is causing us issues. We are going to remove all dependencies on that service since it is not being reliable.

**Comment by christophermurphy2-allscripts** [comment]
I see that formio.js has had the updated CDNs for a while now, any idea when that will make it's way to the 3.x builds for this repo?

**Comment by travist** [comment]
What 3.x builds are you referring too?...  We updated most of the builds to include this new url.

**Comment by christophermurphy2-allscripts** [comment]
The 3.x branch for this repo still has 3.24.0 as the formio.js dependency, and the fix was in 3.24.1 looking at the changelog. Just wondering when ngFormio will get a release with an updated dependency. (Release would have been better wording than build)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
