### ISSUE TITLE
[BUG] Issue with delete actions

### ISSUE THREAD

**Issue by Inaamhusain** [formio/ngFormio#648]
I see there are some issues with formioDelete directive.
There is nothing happening when try to delete actions. I see in ng-formio-helper module using formioDelete directive to delete action with formAction & resourceName attr scope to formioDelete directive. 
After little debugging, I found there is no watcher for formAction and there is a condition to check action variable and it's not getting in to delete particular action.

ng-formio version: 4.0,2

**Comment by jhen1422** [comment]
@Inaamhusain 
Thank you for the report. This is a known issue that is currently on backlog. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by Inaamhusain** [comment]
@jhen1422 is there a way I can contribute?

**Comment by wag110894** [comment]
We welcome pull requests.

**Comment by Inaamhusain** [comment]
I have created new branch and trying to push my code to that branch but it's not working. 
Is there anything in github that you have to add me as a contributer?

**Comment by travist** [comment]
You need to fork the repo, then submit a pull request from your forked repository (which you would certainly have access to).

**Comment by Inaamhusain** [comment]
@travist Thanks for the update.
I have created a pull request with a fixed. You can find that here, [https://github.com/formio/ngFormio/pull/649](https://github.com/formio/ngFormio/pull/649)

**Comment by Inaamhusain** [comment]
@wag110894 @travist Can you please validate pull request which I have mentioned in the above comment.

**Comment by randallknutson** [comment]
The pull request looks good. We'll include it in the next build. Thanks!
