### ISSUE TITLE
Changing the order of pages of Form Wizard

### ISSUE THREAD

**Issue by Morshed0308** [formio/ngFormio#653]
Hello , 
How can I change the order of the pages of wizard ? Like if I have multiple page in a wizard ,how can I change the order of the pages with dragging and dropping. Is there any way to do it? or any other way ?

**Comment by wag110894** [comment]
You will need change the setting from Wizard to Form and reorder the panels to the order you wish.  

Hope this helps.

Thanks.

**Comment by Morshed0308** [comment]
> You will need change the setting from Wizard to Form and reorder the panels to the order you wish.
> 
> Hope this helps.
> 
> Thanks.

Thanks for your reply ! Can you please give a little more details about it ?  Like how can I implement drag and drop in wizard pages so that I can reorder them . I can change the display type to form from wizard but how to make the pages draggable . Thanks in advance.

**Comment by Morshed0308** [comment]
yeah that helped ! Thank you so much!
