### ISSUE TITLE
moving questions from one page to another

### ISSUE THREAD

**Issue by rickjohnson22** [formio/ngFormio#691]
Is there an easy way to move or copy/paste questions from one page to another? The only way I can see doing this by manually recreating them. Not so easy.

**Comment by ccontour** [comment]
Depending on what you are trying to do, you can use the copy button, or edit the json and paste sections from that into another component
<img width="374" alt="Screen Shot 2021-04-09 at 3 34 43 PM" src="https://user-images.githubusercontent.com/35661840/114237779-2a85b480-9949-11eb-8a3f-aa996cf1c21a.png">
<img width="530" alt="Screen Shot 2021-04-09 at 3 34 54 PM" src="https://user-images.githubusercontent.com/35661840/114237782-2b1e4b00-9949-11eb-81b5-62944fefd258.png">

**Comment by rickjohnson22** [comment]
Thanks! I'll give it a shot.
